import { randomUUID } from 'node:crypto'
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { UninstallRemoveAppMode } from '../../shared/uninstall'

export type CleanupRequest = {
  operationId: string
  mainPid: number
  /** App executable path; used as a guard before force-killing on timeout. */
  guardCommandSubstring: string
  /** Validated absolute paths (already passed assertSafeUninstallPath). */
  deleteDataPaths: string[]
  appRemovalMode: UninstallRemoveAppMode
  appRemovalTarget?: string
  platform: NodeJS.Platform
  tempRoot: string
  /** Marker directory that the script removes last (set by writeCleanupScripts). */
  markerDir: string
}

export type CleanupScriptOutput = {
  markerDir: string
  markerPath: string
  scriptPath: string
}

const PID_WAIT_POLLS = 120 // 120 * 0.5s = 60s before the guarded force-kill path
const PID_WAIT_POLL_SECONDS = 0.5
const WINDOWS_WAIT_SECONDS = 90

function shellSingleQuote(value: string): string {
  return `'${value.replace(/'/gu, `'\\''`)}'`
}

function powershellSingleQuote(value: string): string {
  return `'${value.replace(/'/gu, "''")}'`
}

export function buildPosixCleanupScript(request: CleanupRequest): string {
  const lines: string[] = [
    '#!/bin/sh',
    '# Generated by Kun uninstall. Do not edit.',
    'set -u',
    `MAIN_PID=${request.mainPid}`,
    `GUARD=${shellSingleQuote(request.guardCommandSubstring)}`,
    'i=0',
    'while kill -0 "$MAIN_PID" 2>/dev/null; do',
    '  i=$((i+1))',
    `  if [ "$i" -ge ${PID_WAIT_POLLS} ]; then`,
    '    cmd=$(ps -p "$MAIN_PID" -o command= 2>/dev/null || true)',
    '    case "$cmd" in',
    '      *"$GUARD"*) kill -9 "$MAIN_PID" 2>/dev/null || true ;;',
    '    esac',
    '    break',
    '  fi',
    `  sleep ${PID_WAIT_POLL_SECONDS}`,
    'done',
    'sleep 1'
  ]
  for (const path of request.deleteDataPaths) {
    lines.push(`rm -rf -- ${shellSingleQuote(path)}`)
  }
  if (request.appRemovalMode === 'bundle' && request.appRemovalTarget) {
    lines.push(`rm -rf -- ${shellSingleQuote(request.appRemovalTarget)}`)
  } else if (request.appRemovalMode === 'appimage' && request.appRemovalTarget) {
    lines.push(`rm -f -- ${shellSingleQuote(request.appRemovalTarget)}`)
  }
  lines.push(`rm -rf -- ${shellSingleQuote(request.markerDir)}`)
  return `${lines.join('\n')}\n`
}

export function buildWindowsCleanupScript(request: CleanupRequest): string {
  const lines: string[] = [
    '# Generated by Kun uninstall. Do not edit.',
    "$ErrorActionPreference = 'SilentlyContinue'",
    `$mainPid = ${request.mainPid}`,
    `$guard = ${powershellSingleQuote(request.guardCommandSubstring)}`,
    `$deadline = (Get-Date).AddSeconds(${WINDOWS_WAIT_SECONDS})`,
    'while ((Get-Process -Id $mainPid -ErrorAction SilentlyContinue) -and ((Get-Date) -lt $deadline)) {',
    '  Start-Sleep -Milliseconds 500',
    '}',
    'if (Get-Process -Id $mainPid -ErrorAction SilentlyContinue) {',
    '  $proc = Get-CimInstance Win32_Process -Filter "ProcessId = $mainPid"',
    '  if ($proc -and $proc.ExecutablePath -and $proc.ExecutablePath.Contains($guard)) {',
    '    Stop-Process -Id $mainPid -Force',
    '  }',
    '}',
    'Start-Sleep -Seconds 1'
  ]
  for (const path of request.deleteDataPaths) {
    lines.push(`Remove-Item -LiteralPath ${powershellSingleQuote(path)} -Recurse -Force`)
  }
  if (request.appRemovalMode === 'uninstaller' && request.appRemovalTarget) {
    lines.push(`if (Test-Path -LiteralPath ${powershellSingleQuote(request.appRemovalTarget)}) {`)
    lines.push(
      `  Start-Process -FilePath ${powershellSingleQuote(request.appRemovalTarget)} -ArgumentList '/S' -Wait`
    )
    lines.push('}')
  }
  lines.push(`Remove-Item -LiteralPath ${powershellSingleQuote(request.markerDir)} -Recurse -Force`)
  return `${lines.join('\n')}\n`
}

export async function writeCleanupScripts(
  request: Omit<CleanupRequest, 'markerDir'>
): Promise<CleanupScriptOutput> {
  const operationId = request.operationId || randomUUID()
  const markerDir = join(request.tempRoot, `kun-uninstall-${operationId}`)
  await mkdir(markerDir, { recursive: true })
  const isWindows = request.platform === 'win32'
  const scriptName = isWindows ? 'cleanup.ps1' : 'cleanup.sh'
  const scriptPath = join(markerDir, scriptName)
  const markerPath = join(markerDir, 'marker.json')
  const marker = {
    schemaVersion: 1,
    operationId,
    mainPid: request.mainPid,
    guardCommandSubstring: request.guardCommandSubstring,
    deleteDataPaths: request.deleteDataPaths,
    appRemovalMode: request.appRemovalMode,
    appRemovalTarget: request.appRemovalTarget ?? null,
    platform: request.platform,
    createdAt: new Date().toISOString()
  }
  const script = isWindows
    ? buildWindowsCleanupScript({ ...request, operationId, markerDir })
    : buildPosixCleanupScript({ ...request, operationId, markerDir })
  await writeFile(markerPath, `${JSON.stringify(marker, null, 2)}\n`, 'utf8')
  await writeFile(scriptPath, script, 'utf8')
  return { markerDir, markerPath, scriptPath }
}
